version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/aws-codedeploy-demo
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
